.PHONY: build test lint gate

build:
	go build ./...

test:
	go test ./...

lint:
	go vet ./...

# gate — S-67 domain gate. Verifies the whole module builds and every domain
# behavior (BDD) scenario under src/domain/**/model passes with zero failures.
# This is the single command CI runs to keep the domain green.
gate:
	go build ./...
	go vet ./...
	go test ./...
